// POST /api/cron/insert-keywords
// Body: { keywords: KeywordInput[] }
//
// Bulk-inserts keywords from the weekly research routine + monthly audit.
// Duplicates (case-insensitive on keyword) are skipped silently.
// Returns counts so the routine can report what landed.

import { NextRequest } from "next/server";
import { authorizeCronRequest } from "@/lib/cron/auth";
import { db } from "@/lib/supabase/server";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

interface KeywordInput {
  keyword: string;
  volume?: number;
  difficulty?: number;
  intent?: string;
  cluster?: string;
  funnel_stage?: string;
  priority?: "low" | "medium" | "high";
  suggested_title?: string;
  competitor_urls?: string[];
  monetization?: string;
  status?: "idea" | "writing" | "published" | "update";
  linked_post_slug?: string;
}

export async function POST(req: NextRequest) {
  const auth = authorizeCronRequest(req);
  if (!auth.ok) return auth.response!;

  let body: { keywords?: KeywordInput[] };
  try {
    body = await req.json();
  } catch {
    return Response.json({ error: "Invalid JSON body" }, { status: 400 });
  }
  const items = body?.keywords ?? [];
  if (!Array.isArray(items) || items.length === 0) {
    return Response.json({ error: "Provide keywords[]" }, { status: 400 });
  }
  if (items.length > 200) {
    return Response.json({ error: "Max 200 keywords per call" }, { status: 400 });
  }

  // Pull existing keywords once for fast dupe check
  const { data: existing } = await db()
    .from("keywords")
    .select("keyword");
  const have = new Set(
    (existing ?? []).map((r) => r.keyword.toLowerCase().trim())
  );

  let added = 0;
  let skipped = 0;
  const toInsert: Record<string, unknown>[] = [];

  for (const k of items) {
    const kw = (k.keyword ?? "").trim();
    if (!kw) {
      skipped++;
      continue;
    }
    if (have.has(kw.toLowerCase())) {
      skipped++;
      continue;
    }
    have.add(kw.toLowerCase());

    toInsert.push({
      // id auto-generated by DB
      keyword: kw.toLowerCase(),
      volume: k.volume ?? null,
      difficulty: k.difficulty ?? null,
      intent: k.intent ?? null,
      cluster: k.cluster ?? null,
      funnel_stage: k.funnel_stage ?? null,
      priority:
        k.priority ??
        (typeof k.difficulty === "number"
          ? k.difficulty <= 18
            ? "high"
            : k.difficulty <= 30
            ? "medium"
            : "low"
          : "medium"),
      suggested_title: k.suggested_title ?? null,
      competitor_urls: k.competitor_urls ?? [],
      monetization: k.monetization ?? null,
      status: k.status ?? "idea",
      linked_post_slug: k.linked_post_slug ?? null,
    });
    added++;
  }

  if (toInsert.length === 0) {
    return Response.json({ ok: true, added: 0, skipped, received: items.length });
  }

  const { error } = await db().from("keywords").insert(toInsert);
  if (error) {
    return Response.json(
      { error: error.message, attempted: toInsert.length },
      { status: 500 }
    );
  }

  return Response.json({
    ok: true,
    added,
    skipped,
    received: items.length,
  });
}
